# Generated by Django 5.2.7 on 2025-10-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='work_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
